import {
  KasAggregateError,
  Protocol,
  Sdsdk,
  UnwrapDekError,
  Ztdf,
} from "sdsdk";

const COLOR_GREEN = "\x1b[32m";
const COLOR_RESET = "\x1b[0m";
import { loadBasicToken } from "./1_sdk-configuration.js";
import { readFileSync } from "node:fs";

// Load public key for both company
const bobCompanyPK = readFileSync("./public-key/bob-company.pub", "utf8");
/**
 * Initialise an Sdsdk instance to attempt decryption of the
 * `alice-company-confidential-data.ztdf` and `alice-bob-invoice.ztdf`
 * files (located in `examples/base/data/`) using the user `leon.weber`.
 *
 * The file was encrypted with the data attribute `{ team: "finance" }`.
 * Since the user does not belong to the **finance** team, the PDP rule –
 * which requires the user's `team` attribute to match the document's
 * `team` attribute – should deny access.
 *
 * See the relevant policy file:
 *   pdp/policies/rules/bob_kas.regoa
 */
export const sdsdk = new Sdsdk({
  defaultKasId: "bob-company",
  kasList: [
    {
      id: "bob-company",
      protocols: [Protocol.Kas],
      url: "https://bob-company-kmaas:3000/api/v1/b0c6c055-8e61-4cde-ae08-c20a3d9ea3d8/kas",
      authentication: {
        type: "bearer",
        value: await loadBasicToken(
          "bob-company-idp",
          "bob-company",
          "leon.weber",
          "password",
        ),
      },
      publicKey: {
        kid: "f19484ec-3fa2-4603-8de4-afc51d762d30",
        value: bobCompanyPK,
      },
    },
  ],
});

let encryptedFileForAlice: Uint8Array<ArrayBuffer>;
let encryptedFileForAliceAndBob: Uint8Array<ArrayBuffer>;
// Load encrypted .ztdf files generated by the encryption script
try {
  encryptedFileForAlice = readFileSync(
    "./data/alice-company-confidential-data.ztdf",
  );
  encryptedFileForAliceAndBob = readFileSync("./data/alice-bob-invoice.ztdf");
} catch {
  throw new Error(
    "File ./data/alice-company-confidential-data.ztdf and ./data/alice-bob-invoice.ztdf is missing, run encrypt script before",
  );
}

// Attempt to decrypt Alice-only encrypted data (expected to be rejected due to authentication)
try {
  const encryptedFileForAliceZtdf = await Ztdf.fromZip(encryptedFileForAlice);
  await sdsdk.decrypt(encryptedFileForAliceZtdf);
} catch (e) {
  console.log(
    `${COLOR_GREEN}✅ Data decryption rejected – authentication error${COLOR_RESET}`,
  );
  console.error(e);
  console.log("\n");
}

// Attempt to decrypt shared invoice (expected to be rejected by PDP team rule; see /pdp/policies/rules/bob_kas.rego)
try {
  const AliceAndBobInvoiceZtdf = await Ztdf.fromZip(
    encryptedFileForAliceAndBob,
  );
  await sdsdk.decrypt(AliceAndBobInvoiceZtdf);
} catch (e) {
  console.log(
    `${COLOR_GREEN}✅ Data decryption rejected – PDP policy${COLOR_RESET}`,
  );
  console.error(e);
  console.log(`${COLOR_GREEN}✅ KAS error details:${COLOR_RESET}`);
  console.error(((e as UnwrapDekError)?.cause as KasAggregateError).errors);
}
