name: "Stormshield Encryption Platform (exemple)"

x-kas-common: &kas_common
  image: stormshield/kmaas:4.6.0.309 # <-- update with your kmaas image
  environment:
    NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/rootCA.pem
  depends_on:
    cert-generator:
      condition: service_completed_successfully
    keycloak:
      condition: service_healthy
  profiles: [ "sep" ]

services:
  example-base:
    build:
      context: .
      dockerfile: ./examples/base/Dockerfile
    volumes:
      - certs_data:/usr/local/share/ca-certificates
      - ./examples/base/data:/app/data
    environment:
      NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/rootCA.pem
    container_name: base-examples
    profiles: [ "example-base" ]

  alice-company-kmaas:
    <<: *kas_common
    container_name: alice-company-kmaas
    volumes:
      - ./kmaas/alice-company:/etc/stormshield/cse
      - certs_data:/usr/local/share/ca-certificates

  bob-company-kmaas:
    <<: *kas_common
    container_name: bob-company-kmaas
    volumes:
      - ./kmaas/bob-company:/etc/stormshield/cse
      - certs_data:/usr/local/share/ca-certificates

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: idp
    command: [ "start", "--import-realm" ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: idp
      KC_HEALTH_ENABLED: true
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/sep.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/sep-key.pem
    ports:
      - "8443:8443"
    volumes:
      - ./idp/realms:/opt/keycloak/data/import:ro
      - certs_data:/etc/x509/https:ro
    depends_on:
      cert-generator:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "[ -f /tmp/HealthCheck.java ] || echo \"public class HealthCheck {
            public static void main(String[] args) throws Exception {
            javax.net.ssl.HttpsURLConnection.setDefaultHostnameVerifier((s,sess\
            ion)->true); javax.net.ssl.SSLContext sc =
            javax.net.ssl.SSLContext.getInstance(\\\"TLS\\\"); sc.init(null, new
            javax.net.ssl.TrustManager[]{new
            javax.net.ssl.X509TrustManager(){public
            java.security.cert.X509Certificate[] getAcceptedIssuers(){return
            null;} public void
            checkClientTrusted(java.security.cert.X509Certificate[] c, String
            a){} public void
            checkServerTrusted(java.security.cert.X509Certificate[] c, String
            a){}}}, new java.security.SecureRandom());
            javax.net.ssl.HttpsURLConnection.setDefaultSSLSocketFactory(sc.getS\
            ocketFactory()); System.exit(java.net.HttpURLConnection.HTTP_OK ==
            ((java.net.HttpURLConnection)new
            java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 :
            1);}}\" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java
            https://localhost:9000/health/live",
        ]
      interval: 5s
      timeout: 5s
      retries: 30
    profiles: [ "sep" ]

  pdp:
    image: openpolicyagent/opa:1.15.2
    container_name: pdp
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--tls-cert-file=/certs/sep.pem"
      - "--tls-private-key-file=/certs/sep-key.pem"
      - --authentication=token
      - --authorization=basic
      - /policies/rules
      - /policies/auth/authz.rego
      - /policies/auth/data
    ports:
      - "8181:8181"
    volumes:
      - certs_data:/certs
      - ./pdp/policies:/policies
    depends_on:
      cert-generator:
        condition: service_completed_successfully
    profiles: [ "sep" ]

  cert-generator:
    image: alpine/mkcert
    container_name: cert-generator
    entrypoint: [ "sh", "-c" ]
    environment:
      CAROOT: /certs
    command: >
      "mkcert -cert-file /certs/sep.pem -key-file /certs/sep-key.pem localhost
      idp pdp bob-company-kmaas alice-company-kmaas && chmod -R 644
      /certs/*.pem"
    volumes:
      - certs_data:/certs
    restart: "no"
    profiles: [ "sep" ]

volumes:
  certs_data:
